### ISSUE TITLE
建议增加header参数

### ISSUE THREAD

**Issue by beiguancyc** [bluetianx/BirdMessenger#11]
正在使用本开源库，非常好用，感谢。
我在使用其他平台的sdk时，可以分别自定义Metadata和header。
强烈建议增加自定义header

**Comment by bluetianx** [comment]
非常感谢，可以说一下你的具体场景吗？ 因为在build tusclient的时 可以自定义配置 httpClient 的，比如添加header

**Comment by beiguancyc** [comment]
比如在上传时通过header验证身份或传递额外数据。
多谢指点，已经重新pr

**Comment by bluetianx** [comment]
1.如果你打算为每个http请求添加指定的header 比如 身份认证，你应该在build tusclient 时去假如指定的header，这样的话，每次发送请求都会带上这个header
2.如果你想根据 不同的文件 添加不同的 header，这个需求类库暂时没有提供便利的方法去支持，目前只能通过为httpclient 添加一个请求处理handler ，来完成。接下来我会去提供便利的方法。这周我计划先重写TusClientBuild的类

**Comment by beiguancyc** [comment]
多谢您的指点。
先前太大意，仔细查看代码后发现原来TusBuild本身就可以完成添加header，唯一的缺憾是如果不读代码实在是没发现配置隐藏的这么深。

**Comment by bluetianx** [comment]
你也可以看看Wiki文档，有问题随时沟通

**Comment by orangeagain** [comment]
> 你也可以看看Wiki文档，有问题随时沟通

大佬, 请问有两个问题, 一个问题是MetadataCollection是存在Header里的吗?
还一个问题是有没有示例展示一下怎么设置Header呢

**Comment by beiguancyc** [comment]
> > 你也可以看看Wiki文档，有问题随时沟通
> 
> 大佬, 请问有两个问题, 一个问题是MetadataCollection是存在Header里的吗? 还一个问题是有没有示例展示一下怎么设置Header呢
var tusClient = TusBuild.DefaultTusClientBuild(hostUri)
            .Configure(option =>
            {
                ((Microsoft.Extensions.DependencyInjection.ServiceCollection)option.Servces).AddHttpClient(option.ClientName, c =>
                {
                    c.DefaultRequestHeaders.Add("token", xxxxxx);                    
                });
            })
            .Build();

**Comment by bluetianx** [comment]
第二个问题楼主已经回答你了，第一个问题 ： MetaDataCollection 的数据会在创建上传文件链接请求的时候放到 Upload-Metadata 请求头里面，对应的value 就是 MetaData 的数据，每对keyvalue都是逗号 间隔，key value 之间空格隔开，其中value 的值是经过Base64转换的，例如：
`
Upload-Metadata: filename d29ybGRfZG9taW5hdGlvbl9wbGFuLnBkZg==,key value
`

**Comment by orangeagain** [comment]
感谢解答, 可是大大们,可能是版本问题 header加不上啊
这是我的客户端代码:
```
TusDefaultBuilder builder = TusBuild.DefaultTusClientBuild(new Uri(TusServerUrl)).Configure(
            (tusClientOptions, httpClientBuilder) =>
            {
                httpClientBuilder.Services.AddHttpClient(tusClientOptions.FileNameMetadataName, 
                    (configureClient) => {
                        configureClient.DefaultRequestHeaders.Add("testHeader", "thisHeaderValue");
                    }
                    );
            });
        tusClient = builder.Build();
```

服务端:
```
foreach (var h in eventContext.HttpContext.Request.Headers) {
    Console.WriteLine("Headr:"+JsonSerializer.ToJsonString(h));
}
```
服务端接收:
```
Headr:{"Key":"Content-Type","Value":{"Count":1}}
Headr:{"Key":"Host","Value":{"Count":1}}
Headr:{"Key":"Content-Length","Value":{"Count":1}}
Headr:{"Key":"Upload-Offset","Value":{"Count":1}}
Headr:{"Key":"Tus-Resumable","Value":{"Count":1}}
```

更新1:
问题已解决,根据:[2.0的中文文档完全对不上代码](https://github.com/bluetianx/BirdMessenger/issues/21)

另外发现您的回答里有一个bug,
> 第二个问题楼主已经回答你了，第一个问题 ： MetaDataCollection 的数据会在创建上传文件链接请求的时候放到 Upload-Metadata 请求头里面，对应的value 就是 MetaData 的数据，每对keyvalue都是逗号 间隔，key value 之间空格隔开，其中value 的值是经过Base64转换的，例如： `Upload-Metadata: filename d29ybGRfZG9taW5hdGlvbl9wbGFuLnBkZg==,key value`

base64里有"+"、"/" 是不能做文件名的, 我使用这个库把base64转换:[UrlBase64](https://github.com/neosmart/UrlBase64)

更新3:
发现一个bug, client.DefaultRequestHeaders.Add("Cookie", "name1=value1");手动设置cookie无效, 因为UseCookie=true,自动设置了cookie, 导致手动设置cookie会被忽略 详情请见[https://stackoverflow.com/questions/53906224/cant-get-any-cookies-with-c-sharp-httpclient](https://stackoverflow.com/questions/53906224/cant-get-any-cookies-with-c-sharp-httpclient)
没找到本库设置HttpClientHandler.UseCookies的地方, 
~~所以暂时只能用Header代替Cookie了~~,Header 也不能用, 因为Header只能在Build的时候设置一次, 只能使用MetaData了

**Comment by bluetianx** [comment]
你是想在每次调用上传请求的时候都可以加上自定义的header 对吧？目前在Build 中设置的header 会作用于全局的所有请求中，

**Comment by orangeagain** [comment]
新问题，当设置“Authorization”Header时会被忽略, 服务端接收不到
TusRequestOption tusheaders = new TusRequestOption();
tusheaders.HttpHeader["Authorization"] = "xxx";

通过测试这两种修改“Authorization”的方式服务端都可以成功收到，但是BirdMessenger用TusRequestOption的方式设置"Authorization"服务端就收不到“Authorization”
```
using (HttpClient client = new HttpClient())
{
	client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("bear","123");//方法一
        client.DefaultRequestHeaders.Add("Authorization","haha");//方法二
	using (HttpResponseMessage response = await client.GetAsync(CloudSyncManager.UploadUrlPerfix))
	{
		var reponseString = await response.Content.ReadAsStringAsync();
	}
}
```

**Comment by bluetianx** [comment]
认证token 你是打算绑定上 Httpclient 吗？

**Comment by orangeagain** [comment]
> 认证token 你是打算绑定上 Httpclient 吗？
绑定也行，最好是像设置Header一样每次都可以变

目前版本通过TusRequestOption.HttpHeader的方式设置无效会被忽略，可能是要直接设置httpclient的DefaultRequestHeaders才行，但是没找到BirdMessenger在哪设置DefaultRequestHeaders

**Comment by bluetianx** [comment]
参考下面代码
```C#
var tusClient = TusBuild.DefaultTusClientBuild(hostUri)
                .Configure((options, httpClientBuilder) =>
                {
                    httpClientBuilder.ConfigureHttpClient(httpClient =>
                    {
                        httpClient.DefaultRequestHeaders.Authorization =
                            new AuthenticationHeaderValue("Bearer", "ACCESS_TOKEN");
                    });
                })
                .Build();
```
这样配置后，http 请求header会生成这样的请求头： Authorization: Bearer ACCESS_TOKEN
[参考链接](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.headers.authenticationheadervalue.-ctor?view=net-5.0#System_Net_Http_Headers_AuthenticationHeaderValue__ctor_System_String_System_String_)

**Comment by orangeagain** [comment]
> 参考下面代码
> 
> ```cs
> var tusClient = TusBuild.DefaultTusClientBuild(hostUri)
>                 .Configure((options, httpClientBuilder) =>
>                 {
>                     httpClientBuilder.ConfigureHttpClient(httpClient =>
>                     {
>                         httpClient.DefaultRequestHeaders.Authorization =
>                             new AuthenticationHeaderValue("Bearer", "ACCESS_TOKEN");
>                     });
>                 })
>                 .Build();
> ```
> 
> 这样配置后，http 请求header会生成这样的请求头： Authorization: Bearer ACCESS_TOKEN [参考链接](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.headers.authenticationheadervalue.-ctor?view=net-5.0#System_Net_Http_Headers_AuthenticationHeaderValue__ctor_System_String_System_String_)

运行了最新版Demo，不知道为什么服务端还是没有收到“Authorization“那一条😵

服务端Herader Debug Print代码如下，确实没有“Authorization“
```
app.Use(async (context, next) =>
    {
      Console.WriteLine("处理请求IP:" + context.Connection.RemoteIpAddress + "| " 
        + context.Request.GetEncodedUrl(), System.Drawing.Color.Green);
      foreach (var h in context.Request.Headers)
        Console.WriteLine("Header:" + h.Key + ":" + h.Value);
```

**Comment by bluetianx** [comment]
我刚刚测试了一下 ，是有的，
<img width="1095" alt="截屏2021-11-09 22 49 42" src="https://user-images.githubusercontent.com/29353661/140946564-816474fb-51e1-4a62-a2c3-d627a85fd4ba.png">

**Comment by orangeagain** [comment]
找到原因了,可能是http协议不让用token
"http://localhost:5000/upload/"//不行
"https://localhost:5001/upload"//行

**Comment by bluetianx** [comment]
你抓包看看吧，跟http协议无关，我测试的就是http
