### ISSUE TITLE
请问可以支持 NETFramework 吗? 谢谢.

### ISSUE THREAD

**Issue by xjdata** [bluetianx/BirdMessenger#14]

**Comment by bluetianx** [comment]
hi ，抱歉今天才看到，这个类库是基于net standard 2.0 开发，net standard是支持 net framework 4.6.1 及以上。具体可以参考这个文档 [NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard)

**Comment by bluetianx** [comment]
我先关闭这个issue ，未来有什么问题你可以重新打开
