### ISSUE TITLE
2.0的中文文档完全对不上代码

### ISSUE THREAD

**Issue by beiguancyc** [bluetianx/BirdMessenger#21]
如题
建议修改2.0的中文文档

**Comment by bluetianx** [comment]
好的。现在2.0的英文文档是正确的，这周会更新中文文档

**Comment by beiguancyc** [comment]
> 好的。现在2.0的英文文档是正确的，这周会更新中文文档

//upload file
var uploadResult = await tusClient.Upload(fileUrl, fileInfo);
刚发现英文文档也不是全对。。。

**Comment by bluetianx** [comment]
也可以参考 sample 代码。我这边会核对一下文档

**Comment by beiguancyc** [comment]
还有个问题向您请教一下，我原先在使用的时候习惯添加http header，代码如下。2.0版本未找到添加的方法
var tusClient = TusBuild.DefaultTusClientBuild(hostUri)
            .Configure(option =>
            {
                ((Microsoft.Extensions.DependencyInjection.ServiceCollection)option.Servces).AddHttpClient(option.ClientName, c =>
                {
                    c.DefaultRequestHeaders.Add("token", "12345");
                });
            })
            .Build();

**Comment by bluetianx** [comment]
``` C#
var tusClient = TusBuild.DefaultTusClientBuild(hostUri)
                .Configure((options,builder) =>
                {
                    builder.ConfigureHttpClient((serviceProiver, client) =>
                    {
                        client.DefaultRequestHeaders.Add("token", "12345");
                    })
                })
                .Build();
```
参考这个代码

**Comment by bluetianx** [comment]
你的项目中要是用了 IServiceCollection 进行依赖注入的话 ，建议你看看ServiceCollectionExtensions 这个类的扩展方法，可以与你的依赖注入结合在一起
