### ISSUE TITLE
奇怪的错误creation response statusCode is BadRequest

### ISSUE THREAD

**Issue by beiguancyc** [bluetianx/BirdMessenger#28]
您好，使用BirdMessenger为我解决了不少问题，非常感谢。
但是最近上传一批文件时全都上传失败，
执行到var fileUrl = await tusClient.Create(fileInfo);
返回creation response statusCode is BadRequest
这批文件都大于70M，使用2.0.1都无法上传。我试了下小文件可以。
1.0.1的BirdMessenger大文件小文件都没问题
百思不得其解，希望您能帮忙，代码如下

         FileInfo fileInfo = new FileInfo(filePath);                      
            var hostUri = new Uri("http://"+ appConfig.AppConfigGet("serverhost") + ":6008/uploads");            
            var tusClient = TusBuild.DefaultTusClientBuild(hostUri)
                .Configure((options, builder) =>
                {
                    builder.ConfigureHttpClient((serviceProiver, client) =>
                    {                        
                        if (dict != null)
                        {
                            dict.Keys.ForEach(t =>
                            {
                                client.DefaultRequestHeaders.Add(t, dict[t]);
                            });
                        }
                    });
                })            
            .Build();

            tusClient.UploadProgress += TusClient_UploadProgress; 
            tusClient.UploadFinish += TusClient_UploadFinish;          

            var fileUrl = await tusClient.Create(fileInfo);
            var uploadResult = await tusClient.Upload(fileUrl, fileInfo, null);

**Comment by bluetianx** [comment]
2.0.0版本可以吗

**Comment by bluetianx** [comment]
我这边测试了一下，没有发现问题，你这个 if (dict != null)
                    {
                        dict.Keys.ForEach(t =>
                        {
                            client.DefaultRequestHeaders.Add(t, dict[t]);
                        });
                    }
dic 参数值是多少

**Comment by beiguancyc** [comment]
> 我这边测试了一下，没有发现问题，你这个 if (dict != null)
> {
> dict.Keys.ForEach(t =>
> {
> client.DefaultRequestHeaders.Add(t, dict[t]);
> });
> }
> dic 参数值是多少

三个string。尝试了下2.0.0，也是报同样的错。而且我用开发测试机（Mac os）做tus服务端没问题，挪到正式服务器（Windows）就报这个错误。如果BirdMessenger1.x则都没有问题。
Dictionary<string, string> dict = new Dictionary<string, string>();
dict["token"] ="xxxxxxxx";
dict["prtkey"] = saveKey;
dict["originalname"] = fileName;

**Comment by bluetianx** [comment]
你要是能提供一些http抓包的数据就更好了，还有把你的tus 服务端用的版本和语言提供一下

**Comment by beiguancyc** [comment]
> 你要是能提供一些http抓包的数据就更好了，还有把你的tus 服务端用的版本和语言提供一下

没问题，一定提供。服务端用的node，使用的"tus-node-server": "^0.3.2"，上传的时候通过header里的token验证。token是通过jwt加密的一个string。
1.x和2.x使用的服务端是一样的，客户端代码略有不同，但都是基本照抄wiki。
我是这么想的，
1.x完全没问题，说明服务端设置上没有问题。
2.x小文件可以上传，说明服务端上传和验证是没问题的
抓包数据请稍等一下

**Comment by bluetianx** [comment]
大文件的话，第一步创建url 就报错 对吗？

**Comment by beiguancyc** [comment]
执行到await tusClient.Create(fileInfo);报错

**Comment by bluetianx** [comment]
> 抓包数据请稍等一下

等你抓包结果吧

**Comment by beiguancyc** [comment]
> > 抓包数据请稍等一下
> 
> 等你抓包结果吧

不好意思，前段时间被派出去出差了，刚回来测试了下。挂上fiddler后发现上传一切正常，关掉fiddler后也正常。。。
这段时间内，客户端和服务端，服务器均没有发生任何改动，只能说是灵异现象了。
