### ISSUE TITLE
请问BirdMessenger支持Concatenation扩展吗？

### ISSUE THREAD

**Issue by bidw77** [bluetianx/BirdMessenger#30]
您好，非常感谢，您的BirdMessenger给我提供了很大的帮助，下个版本能支持Concatenation扩展吗？

**Comment by bluetianx** [comment]
你能详细说说 Concatenation 扩展吗

**Comment by bidw77** [comment]
https://tus.io/protocols/resumable-upload.html

**Comment by bidw77** [comment]
这样就可以多线程分块上传，后合并。早上试了下，post返回400

**Comment by bluetianx** [comment]
可以考虑支持，能说一下你的应用场景吗，因为大部分场景上传一个文件单线程就可以满足了

**Comment by bidw77** [comment]
项目上传的文件比较大（一般都在300M~1G），单线程上传一个文件时间需要好久。客户希望提高上传速度。

**Comment by li-zhixin** [comment]
+1
我们也遇到了相同的问题

**Comment by bluetianx** [comment]
copy that

**Comment by bluetianx** [comment]
下个版本就可以支持了

**Comment by ginahanyu** [comment]
+1
同样期待这个feature.

**Comment by bluetianx** [comment]
hi ,目前暂时还没支持这个扩展的计划，因为这个特性并不能很好的提升上传效率，tus 协议2.0的版本也没有对这个特性进行改进。不过我新发布了新版本2.2，这个版本很好地提升了文件上传效率。简单的示例代码如下，完整的示例可以看这个项目的主页。

``` C#
var uploadOpt = new TusRequestOption()
 {
      UploadWithStreaming = true //enable streaming Upload
 };

 //upload file
 var uploadResult = await tusClient.Upload(fileUrl, fileInfo, null,uploadOpt);
```

**Comment by bluetianx** [comment]
@bidw77 @li-zhixin  我先关闭了这个issue ，以后有什么问题你们可以重新打开这个issue
