### ISSUE TITLE
请问支持断点续传吗

### ISSUE THREAD

**Issue by orangeagain** [bluetianx/BirdMessenger#31]
如题, 主要用在Unity客户端上

**Comment by bluetianx** [comment]
你好，该组件是基于net standard 2.0 开发的，可以在mono 5.4 及以上的版本上运行，这是net standard 支持详情https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by orangeagain** [comment]
感谢回复，unity应该是可以用的。但是没看到如何断点续传的文档，请问目前支持断点续传吗

**Comment by bluetianx** [comment]
该组件就是支持断点续传的

**Comment by orangeagain** [comment]
可是上传一个文件, 中途断掉. 重启客户端再上传同一个文件, 在服务端是两个文件, 并没有从上次断掉的地方开始. 是不是我使用方式不对导致的

**Comment by orangeagain** [comment]
刚才试了, Unity3D没有`Microsoft.Extensions.DependencyInjection`, 所以并不支持Unity

**Comment by bluetianx** [comment]
Microsoft.Extensions.DependencyInjection  ，这个nuget 包也是支持net standard 2.0 的，

**Comment by orangeagain** [comment]
一口气导入了13个DLL, ~~Unity编辑器直接卡死, 算了, 我还是直接用HttpClient上传吧~~
然后上传成功了, 就是必须用Async方法😃👍

**Comment by bluetianx** [comment]
async 可以提高你的性能的，😂

**Comment by bluetianx** [comment]
> 一口气导入了13个DLL

这个包可以帮组你更好的开发面向接口的编程的代码，以后你可以经常用起来啦 😁

**Comment by orangeagain** [comment]
> > 一口气导入了13个DLL
> 
> 这个包可以帮组你更好的开发面向接口的编程的代码，以后你可以经常用起来啦 😁

恩, 以后要用在生产版本中了. 断点续传也搞明白了, 往同一个Uri传就可以续传
