### ISSUE TITLE
权限验证不可用 Authority Unavailable

### ISSUE THREAD

**Issue by orangeagain** [bluetianx/BirdMessenger#32]
方案1: MetaData
权限信息存在MetaData里. 考虑过后发现不可行.
因为TusClient.Upload()方法里 也就是服务端GetFileInfo 和 WriteFile 接口,  客户端根本就没有发送"Upload-Metadata"的header, 所以不可行.

方案2: Cookie
手动设置cookie无效, 因为UseCookie=true,系统会自动设置cookie, 导致手动设置cookie会被忽略 详情请见[https://stackoverflow.com/questions/53906224/cant-get-any-cookies-with-c-sharp-httpclient](https://stackoverflow.com/questions/53906224/cant-get-any-cookies-with-c-sharp-httpclient)目前没发现本库怎么设置UseCookie属性, 并且也没有发现怎么设置每次不同的Cookie. 所以暂时不可行

方案3: Header
目前没发现怎么设置每次不同的自定义Header, 所以暂时不可行

请问大佬您是如何解决权限验证问题的呢?  是否考虑增加每次设置Header或Cookie呢?

**Comment by bluetianx** [comment]
>  方案3: Header
目前没发现怎么设置每次不同的自定义Header, 所以暂时不可行
请问大佬您是如何解决权限验证问题的呢? 是否考虑增加每次设置Header或Cookie呢?

目前确实暂时不支持每次上传都传输自定义的header，后面我会加上这个功能，临时解决办法：你可以每次上传前都build 一个新的tusclient 实例来解决，在Build 中传入自定义的header

**Comment by bluetianx** [comment]
> 方案1: MetaData
权限信息存在MetaData里. 考虑过后发现不可行.
因为TusClient.Upload()方法里 也就是服务端GetFileInfo 和 WriteFile 接口, 客户端根本就没有发送"Upload-Metadata"的header, 所以不可行.

Upload-Metadata 支持会在create 上传文件url 的时候才能传入，后续的断点续传不会携带该header

**Comment by bluetianx** [comment]
>方案2: Cookie
手动设置cookie无效, 因为UseCookie=true,系统会自动设置cookie, 导致手动设置cookie会被忽略 详情请见https://stackoverflow.com/questions/53906224/cant-get-any-cookies-with-c-sharp-httpclient目前没发现本库怎么设置UseCookie属性, 并且也没有发现怎么设置每次不同的Cookie. 所以暂时不可行


参考下面：
[原文链接](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-5.0)
>Cookies
The pooled HttpMessageHandler instances results in CookieContainer objects being shared. Unanticipated CookieContainer object sharing often results in incorrect code. For apps that require cookies, consider either:

Disabling automatic cookie handling
Avoiding IHttpClientFactory
Call ConfigurePrimaryHttpMessageHandler to disable automatic cookie handling:

C#

Copy
services.AddHttpClient("configured-disable-automatic-cookies")
    .ConfigurePrimaryHttpMessageHandler(() =>
    {
        return new HttpClientHandler()
        {
            UseCookies = false,
        };
    });

**Comment by orangeagain** [comment]
> > 方案3: Header
> > 目前没发现怎么设置每次不同的自定义Header, 所以暂时不可行
> > 请问大佬您是如何解决权限验证问题的呢? 是否考虑增加每次设置Header或Cookie呢?
> 
> 目前确实暂时不支持每次上传都传输自定义的header，后面我会加上这个功能，临时解决办法：你可以每次上传前都build 一个新的tusclient 实例来解决，在Build 中传入自定义的header

但是不知道每次build出的httpclient占用的端口是否释放，如果是同一个httpclient实例还好。如果每次build都新开一个端口的话很快爆炸

**Comment by orangeagain** [comment]
> > 方案1: MetaData
> > 权限信息存在MetaData里. 考虑过后发现不可行.
> > 因为TusClient.Upload()方法里 也就是服务端GetFileInfo 和 WriteFile 接口, 客户端根本就没有发送"Upload-Metadata"的header, 所以不可行.
> 
> Upload-Metadata 支持会在create 上传文件url 的时候才能传入，后续的断点续传不会携带该header

这样没有验证的话，任何用户都可以虚传其他用户的文件，只要猜到其他用户的fileid，有隐患。。。

**Comment by bluetianx** [comment]
> > > 方案3: Header
> > > 目前没发现怎么设置每次不同的自定义Header, 所以暂时不可行
> > > 请问大佬您是如何解决权限验证问题的呢? 是否考虑增加每次设置Header或Cookie呢?
> > 
> > 
> > 目前确实暂时不支持每次上传都传输自定义的header，后面我会加上这个功能，临时解决办法：你可以每次上传前都build 一个新的tusclient 实例来解决，在Build 中传入自定义的header
> 
> 但是不知道每次build出的httpclient占用的端口是否释放，如果是同一个httpclient实例还好。如果每次build都新开一个端口的话很快爆炸

这个不用担心，现在新版的Httpclient 都是基于Factory的，你可以试用一下，你这个增加自定义header 需求我尽量这周完成

**Comment by bluetianx** [comment]
> > > 方案1: MetaData
> > > 权限信息存在MetaData里. 考虑过后发现不可行.
> > > 因为TusClient.Upload()方法里 也就是服务端GetFileInfo 和 WriteFile 接口, 客户端根本就没有发送"Upload-Metadata"的header, 所以不可行.
> > 
> > 
> > Upload-Metadata 支持会在create 上传文件url 的时候才能传入，后续的断点续传不会携带该header
> 
> 这样没有验证的话，任何用户都可以虚传其他用户的文件，只要猜到其他用户的fileid，有隐患。。。

你的需求是每个上传都要传一个特定的权限token吗？我认为每一个用户client 只用一个token就行，同一个用户上传不同的问题不用每次都变更token

**Comment by orangeagain** [comment]
> 你的需求是每个上传都要传一个特定的权限token吗？我认为每一个用户client 只用一个token就行，同一个用户上传不同的问题不用每次都变更token

需求是验证访问续传接口的用户是否合法, 续传接口没有MetaData,所以只能用cookie或header

> 这个不用担心，现在新版的Httpclient 都是基于Factory的，你可以试用一下，你这个增加自定义header 需求我尽量这周完成

🙏非常感谢您的努力!  期待新版本

**Comment by bluetianx** [comment]
> 需求是验证访问续传接口的用户是否合法, 续传接口没有MetaData,所以只能用cookie或header

一般身份验证的token 可以考虑再Bulid 的时候传入，每个用户有自己的http client，自定义header 的功能我尽快这周完成

**Comment by bluetianx** [comment]
@orangeagain  我现在上传了新的版本， 2.1.0-bata. ，你可以测试一下看看

**Comment by orangeagain** [comment]
> @orangeagain 我现在上传了新的版本， 2.1.0-bata. ，你可以测试一下看看

测试成功👍, 感谢您的努力

**Comment by bluetianx** [comment]
后面发布了正式版，我在和你说，这个期间有什么问题可以及时跟我沟通

**Comment by orangeagain** [comment]
> 后面发布了正式版，我在和你说，这个期间有什么问题可以及时跟我沟通

有个小问题 is not null 语法在unity不支持, 改成 != null可用. 

还有进度回调函数在build tus client时就确定了, 可是我的项目可能会多线程多对象共用一个 TusClient, 能不能进度回调的作用域在单次Upload里传入,  Upload运行完就释放呢

**Comment by bluetianx** [comment]
> 还有进度回调函数在build tus client时就确定了, 可是我的项目可能会多线程多对象共用一个 TusClient, 能不能进度回调的作用域在单次Upload里传入, Upload运行完就释放呢

tus client 最好不要多线程使用，并行上传多个文件就创建多个tus client

**Comment by bluetianx** [comment]
> 有个小问题 is not null 语法在unity不支持, 改成 != null可用.

我晚上看看

**Comment by bluetianx** [comment]
>有个小问题 is not null 语法在unity不支持, 改成 != null可用.

@orangeagain  你是通过引用nuget 包使用 还是通过引用源码使用的？

**Comment by orangeagain** [comment]
> > 有个小问题 is not null 语法在unity不支持, 改成 != null可用.
> 
> @orangeagain 你是通过引用nuget 包使用 还是通过引用源码使用的？

用的源码放在Unity工程里面, 缺的.net core 依赖用dll引用的

**Comment by bluetianx** [comment]
> 用的源码放在Unity工程里面, 缺的.net core 依赖用dll引用的

你应该直接用nuget 网站里面的nuget 包，这样就不会出现你说的问题了

**Comment by orangeagain** [comment]
Unity不支持nuget包, 下次我试试直接Dll导入. 
Cookie的事, 我是直接改源码, 在ServiceCollectionExtensions.cs 30行加入:
```
.ConfigurePrimaryHttpMessageHandler(() =>
            {
              return new HttpClientHandler()
              {
                UseCookies = false,
              };
            });
```
要是有更好的办法就好了

**Comment by orangeagain** [comment]
Unity不支持nuget包, 下次我试试直接Dll导入. ServiceCollectionExtensions.cs

**Comment by bluetianx** [comment]
下面这行代码是可以在build 方法里面加进去的

`.ConfigurePrimaryHttpMessageHandler(() =>
            {
              return new HttpClientHandler()
              {
                UseCookies = false,
              };
            });`

**Comment by bluetianx** [comment]
我后面给你个示例

**Comment by bluetianx** [comment]
参考下面代码 @orangeagain 

```C#
 var tusClient = TusBuild.DefaultTusClientBuild(hostUri)
                .Configure((options, httpClientBuilder) =>
                {
                    //customize http client
                    httpClientBuilder.ConfigureHttpClient(httpClient =>
                    {
                        httpClient.DefaultRequestHeaders.Authorization =
                            new AuthenticationHeaderValue("Bearer", "ACCESS_TOKEN");
                        
                    });
                    httpClientBuilder.ConfigurePrimaryHttpMessageHandler(() => new HttpClientHandler()
                    {
                        UseCookies = false,
                    });
                })
                .Build();
```
