### ISSUE TITLE
上传1.9G文件报错patch response statusCode is NotFound

### ISSUE THREAD

**Issue by bidw77** [bluetianx/BirdMessenger#34]
今天在正式环境测试发现上传1.9G的文件客户端报错，但文件在tusfiles目录里存在，并且上传文件是完整的，服务端OnFileCompleteAsync日志记录正常结束。900M文件上传成功无报错！
2021-11-13 19:11:30   [13]   ERROR   FileStoreCore.FileNetClient.Upload  BirdMessenger.Infrastructure.TusException: patch response statusCode is NotFound
   在 BirdMessenger.Core.Tus.<Patch>d__3.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 BirdMessenger.TusClient.<Upload>d__14.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 BirdMessenger.TusClient.<Upload>d__15.MoveNext()

**Comment by bidw77** [comment]
再次测试1.2G可正常上传完成，正常返回。1.5G的文件已上传成功，却返回patch response statusCode is NotFound，这种情况发生在文件上传的最后一包。

**Comment by bluetianx** [comment]
404 响应码是服务端没找到对应的文件，原因可能是： 1.服务端设置了文件过期时间； 2.上传的url不正确

**Comment by bidw77** [comment]
过期时间我设置的是1小时。问题出现在大于1G的文件,出现错误是上传文件的最后一包的patch请求。低于1G的文件上传成功。
我在tusdotnet也提问了：https://github.com/tusdotnet/tusdotnet/issues/155

**Comment by bluetianx** [comment]
每次都能复现吗？请说一下你用的代码运行环境，以及版本

**Comment by bidw77** [comment]
net5 (linux centos7)
是的。只要超过1G的文件，必现。

**Comment by bluetianx** [comment]
我这边上传的文件大多都是好几个G的文件，你先尝试能不能在本机复现，这个nofound 异常是服务端给出的，问题一般在服务端

**Comment by bidw77** [comment]
问题找到了。是nginx连接超时的问题。重新设置proxy_read_timeout、proxy_send_timeout、proxy_connect_timeout设置成180，1.9G上传成功。
4.6G还是失败，nginx状态码499，最后一包耗时1分40秒，这个可能是HttpClient等待超时问题（客户端不等待响应，关闭了连接）。请提供下超时设置。

**Comment by bluetianx** [comment]
wiki 里面有写

**Comment by bidw77** [comment]
感谢！那我关闭了！
