### ISSUE TITLE
同步方法调用异步方法卡死问题！

### ISSUE THREAD

**Issue by bidw77** [bluetianx/BirdMessenger#36]
希望在await后的异步调用，都加上ConfigureAwait(false).避免锁死。

**Comment by bluetianx** [comment]
你这个操作本身就是错误的，属于异步开发的经典错误问题

**Comment by bidw77** [comment]
全异步不会有问题，但因为是旧项目，存在同步方法调用异步的问题。意见加上。不知对不对。以下是我找的一些资料。
https://www.cnblogs.com/xiaoxiaotank/p/13529413.html
通用库之所以成为“通用库”，原因之一是因为它们不关心使用它们的环境。您可以在Web应用程序、客户端应用程序或测试程序中使用它们，这无关紧要，因为库代码与可能使用的应用程序模型无关。那么，无关就意味着它不会做任何需要以特定方式与应用程序模型进行交互的事情，例如：它不会访问UI控件，因为通用库对UI控件一无所知。由于我们不需要在任何特定环境中运行代码，那么我们可以避免将回调强制送回到原始上下文，这可以通过使用ConfigureAwait(false)来实现，并享受到其带来的性能和可靠性优势。这形成了以下一般指导：如果要编写通用库代码，请使用ConfigureAwait(false)。这就是为什么您会在.NET Core运行时库中看到每个（或几乎每个）await时都要使用ConfigureAwait(false)的原因；如果不是这样的话（除了少数例外），那很可能是一个要修复的BUG。例如，此Pull request修复了HttpClient中缺少的ConfigureAwait(false)调用。

看一下mono的HttpClient源代码，可以发现：

所有await 表达式后面，都加了ConfigureAwait (false)，如

return await resp.Content.ReadAsStringAsync ().ConfigureAwait (false);

而由Task的msdn文档可以知，ConfigureAwait (false)会指示await之后的代码不在原先的context （可理解为线程）上运行。

**Comment by bidw77** [comment]
在项目中遇到各种问题。后来同步方法调用异步方法，采用消息泵才得以解决。
/// <summary>Provides a pump that supports running asynchronous methods on the current thread.</summary>
    public static class AsyncPump
    {
        /// <summary>Runs the specified asynchronous method.</summary>
        /// <param name="asyncMethod">The asynchronous method to execute.</param>
        public static void Run(Action asyncMethod)
        {
            if (asyncMethod == null) throw new ArgumentNullException("asyncMethod");

            var prevCtx = SynchronizationContext.Current;
            try
            {
                // Establish the new context
                var syncCtx = new SingleThreadSynchronizationContext(true);
                SynchronizationContext.SetSynchronizationContext(syncCtx);

                // Invoke the function
                syncCtx.OperationStarted();
                asyncMethod();
                syncCtx.OperationCompleted();

                // Pump continuations and propagate any exceptions
                syncCtx.RunOnCurrentThread();
            }
            finally { SynchronizationContext.SetSynchronizationContext(prevCtx); }
        }

        /// <summary>Runs the specified asynchronous method.</summary>
        /// <param name="asyncMethod">The asynchronous method to execute.</param>
        public static void Run(Func<Task> asyncMethod)
        {
            if (asyncMethod == null) throw new ArgumentNullException("asyncMethod");

            var prevCtx = SynchronizationContext.Current;
            try
            {
                // Establish the new context
                var syncCtx = new SingleThreadSynchronizationContext(false);
                SynchronizationContext.SetSynchronizationContext(syncCtx);

                // Invoke the function and alert the context to when it completes
                var t = asyncMethod();
                if (t == null) throw new InvalidOperationException("No task provided.");
                t.ContinueWith(delegate { syncCtx.Complete(); }, TaskScheduler.Default);

                // Pump continuations and propagate any exceptions
                syncCtx.RunOnCurrentThread();
                t.GetAwaiter().GetResult();
            }
            finally { SynchronizationContext.SetSynchronizationContext(prevCtx); }
        }

        /// <summary>Runs the specified asynchronous method.</summary>
        /// <param name="asyncMethod">The asynchronous method to execute.</param>
        public static T Run<T>(Func<Task<T>> asyncMethod)
        {
            if (asyncMethod == null) throw new ArgumentNullException("asyncMethod");

            var prevCtx = SynchronizationContext.Current;
            try
            {
                // Establish the new context
                var syncCtx = new SingleThreadSynchronizationContext(false);
                SynchronizationContext.SetSynchronizationContext(syncCtx);

                // Invoke the function and alert the context to when it completes
                var t = asyncMethod();
                if (t == null) throw new InvalidOperationException("No task provided.");
                t.ContinueWith(delegate { syncCtx.Complete(); }, TaskScheduler.Default);

                // Pump continuations and propagate any exceptions
                syncCtx.RunOnCurrentThread();
                return t.GetAwaiter().GetResult();
            }
            finally { SynchronizationContext.SetSynchronizationContext(prevCtx); }
        }

        /// <summary>Provides a SynchronizationContext that's single-threaded.</summary>
        private sealed class SingleThreadSynchronizationContext : SynchronizationContext
        {
            /// <summary>The queue of work items.</summary>
            private readonly BlockingCollection<KeyValuePair<SendOrPostCallback, object>> m_queue =
                new BlockingCollection<KeyValuePair<SendOrPostCallback, object>>();
            /// <summary>The processing thread.</summary>
            private readonly Thread m_thread = Thread.CurrentThread;
            /// <summary>The number of outstanding operations.</summary>
            private int m_operationCount = 0;
            /// <summary>Whether to track operations m_operationCount.</summary>
            private readonly bool m_trackOperations;

            /// <summary>Initializes the context.</summary>
            /// <param name="trackOperations">Whether to track operation count.</param>
            internal SingleThreadSynchronizationContext(bool trackOperations)
            {
                m_trackOperations = trackOperations;
            }

            /// <summary>Dispatches an asynchronous message to the synchronization context.</summary>
            /// <param name="d">The System.Threading.SendOrPostCallback delegate to call.</param>
            /// <param name="state">The object passed to the delegate.</param>
            public override void Post(SendOrPostCallback d, object state)
            {
                if (d == null) throw new ArgumentNullException("d");
                m_queue.Add(new KeyValuePair<SendOrPostCallback, object>(d, state));
            }

            /// <summary>Not supported.</summary>
            public override void Send(SendOrPostCallback d, object state)
            {
                throw new NotSupportedException("Synchronously sending is not supported.");
            }

            /// <summary>Runs an loop to process all queued work items.</summary>
            public void RunOnCurrentThread()
            {
                foreach (var workItem in m_queue.GetConsumingEnumerable())
                    workItem.Key(workItem.Value);
            }

            /// <summary>Notifies the context that no more work will arrive.</summary>
            public void Complete() { m_queue.CompleteAdding(); }

            /// <summary>Invoked when an async operation is started.</summary>
            public override void OperationStarted()
            {
                if (m_trackOperations)
                    Interlocked.Increment(ref m_operationCount);
            }

            /// <summary>Invoked when an async operation is completed.</summary>
            public override void OperationCompleted()
            {
                if (m_trackOperations &&
                    Interlocked.Decrement(ref m_operationCount) == 0)
                    Complete();
            }
        }
    }

**Comment by bluetianx** [comment]
> 全异步不会有问题

异步调用异步是不会出现上面提到的死锁问题。同步调用异步会出现死锁的情况的，不提倡同步调用异步，

> 通用库之所以成为“通用库”，原因之一是因为它们不关心使用它们的环境。您可以在Web应用程序、客户端应用程序或测试程序中使用它们，这无关紧要，因为库代码与可能使用的应用程序模型无关。

同步调用异步存在死锁风险是需要使用者去分析评估的，**更重要的是，同步调用异步存在死锁的情况是每个程序员应该熟知的事情** ，你可以看一下[异步编程案例](https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md)

**Comment by bidw77** [comment]
感谢回复！
