### ISSUE TITLE
Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions

### ISSUE THREAD

**Issue by saravana128** [bluetianx/BirdMessenger#37]
While we try to run the code in different Enviroment(Outsystem)
We are Facing this exception during runtime. .Net Version standard 2.2.0.0
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.File name: 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'   at BirdMessenger.TusBuild.DefaultTusClientBuild(Action`1 configure)   at BirdMessenger.TusBuild.DefaultTusClientBuild(Uri tusHost)

**Comment by bluetianx** [comment]
add nuget package Microsoft.Extensions.DependencyInjection.Abstractions to your code project , it may resolve your problem

**Comment by saravana128** [comment]
Even After adding the nuget package reference. The issue is not Resolved

**Comment by bluetianx** [comment]
please tell me about version of dotnet  and OS

**Comment by saravana128** [comment]
Generated the dll with .NET Core 2.2.8 on windows 10
Running on Windows Server OS(2016) with .Net Core 2.1.30

**Comment by bluetianx** [comment]
can you reproduce this problem in your develop environment ?

**Comment by saravana128** [comment]
Downgraded the library version to 2.1.1. Now its works fine

**Comment by bluetianx** [comment]
ok ，I am so glad to hear that ,welcome to star
