### ISSUE TITLE
Upload Result

### ISSUE THREAD

**Issue by SebastianStehle** [bluetianx/BirdMessenger#38]
Hi,

thanks for this library. I consider to integrate it into my project, but I have the following issue:

When I upload something I need the result of the request. I think the Tus protocol does not allow to change the response to a none-204 status code, but I could add a header with information to point me to the created resource.

At the moment the Tus Client only returns bool, so I cannot access the header. It is also cofusing what "bool" actually means in this context.

**Comment by bluetianx** [comment]
> It is also cofusing what "bool" actually means in this context.

true means the file has finished upload，false means the file has not finished

**Comment by SebastianStehle** [comment]
But is this is not what an exception is for?

**Comment by bluetianx** [comment]
> but I could add a header with information to point me to the created resource.
 client not support this feature  currently, I will consider this  feature

**Comment by bluetianx** [comment]
> But is this is not what an exception is for?

I do not understand this problem.  can you give me an example ?

**Comment by SebastianStehle** [comment]
I just mean that it is very unexpected to have bool as a result in a .NET API. Most other APIs either result more information or just bubble up the exception.

What does false mean?

* Network problem?
* Http Error? Which status code?
* SSL Issue?

From looking at the code. False mean "NotCancelled".

**Comment by bluetianx** [comment]
> * Network problem?
> * Http Error? Which status code?
> * SSL Issue?

client  will throw exception if incur other cases

**Comment by bluetianx** [comment]
> What does false mean?

You interrupted the upload by cancelToken and the file has not finished

**Comment by bluetianx** [comment]
> From looking at the code. False mean "NotCancelled".

nope, it mean "Cancelled"

**Comment by SebastianStehle** [comment]
Yes, ofc
