### ISSUE TITLE
Stream result to server

### ISSUE THREAD

**Issue by SebastianStehle** [bluetianx/BirdMessenger#39]
Hi,

Why do you need to make the chunking here?

https://github.com/bluetianx/BirdMessenger/blob/master/src/BirdMessenger/TusClient.cs#L88

Can you not just stream the results to the server.

**Comment by bluetianx** [comment]
tus protocol is a resume upload protocol. client can only upload files piece by piece ，
This is protocol example

```C#
Request:

PATCH /files/24e533e02ec3bc40c387f1a0e460e216 HTTP/1.1
Host: tus.example.org
Content-Type: application/offset+octet-stream
Content-Length: 30
Upload-Offset: 70
Tus-Resumable: 1.0.0

[remaining 30 bytes]
Response:

HTTP/1.1 204 No Content
Tus-Resumable: 1.0.0
Upload-Offset: 100
```

**Comment by SebastianStehle** [comment]
I think this is wrong in my opinion. it is not stated in the documentation that you can only upload chunk by chunk. This results in much more requests than needed.

Typically you wanna upload everything in one request and in the case of an interruption you want to proceed from where you have been.

**Comment by bluetianx** [comment]
> Typically you wanna upload everything in one request and in the case of an interruption you want to proceed from where you have been.

if you have a large file ,for example :it is more than 10GB, You will fail by one request.  you can set chunk size if you want to upload file in one request

**Comment by bluetianx** [comment]
Tus was created for resolving largest file upload not small file uploaded by one request

**Comment by bluetianx** [comment]
> it is not stated in the documentation that you can only upload chunk by chunk.

 you can find it in the Protocol Doc
```C#
Request:

PATCH /files/24e533e02ec3bc40c387f1a0e460e216 HTTP/1.1
Host: tus.example.org
Content-Type: application/offset+octet-stream
Content-Length: 30
Upload-Offset: 70
Tus-Resumable: 1.0.0

[remaining 30 bytes]
Response:

HTTP/1.1 204 No Content
Tus-Resumable: 1.0.0
Upload-Offset: 100
````

**Comment by SebastianStehle** [comment]
> The Client SHOULD send all the remaining bytes of an upload in a single PATCH request, but MAY also use multiple small requests successively for scenarios where this is desirable. One example for these situations is when the [Checksum](https://tus.io/protocols/resumable-upload.html#checksum) extension is used.

From the docs.

**Comment by bluetianx** [comment]
> > The Client SHOULD send all the remaining bytes of an upload in a single PATCH request, but MAY also use multiple small requests successively for scenarios where this is desirable. One example for these situations is when the [Checksum](https://tus.io/protocols/resumable-upload.html#checksum) extension is used.
> 
> From the docs.

yep ，SHOULD not MUST , you can set Upload size if you want to upload file in one request. If you upload largest file ,I suggest you use multiple small requests

**Comment by bluetianx** [comment]
If you always want to upload file in one request, I think you should  use http client directly.

**Comment by SebastianStehle** [comment]
I have not said that. I think you should make as few requests as possible to get the upload speed up. A typically ping is 30 to 50ms, so you loose these milliseconds between each chunk. A 100ms ping means 10MB/sec, a 200ms PING means 5MB/sec and so on.

Your chunk size is 1MB, which means you cannot get a higher upload speed than 20MB / sec. Even if your upload of a single chunk is instant.

**Comment by bluetianx** [comment]
> A typically ping is 30 to 50ms

Different users have different Bandwidth.
> A 100ms ping means 10MB/sec, a 200ms PING means 5MB/sec and so on.

I do not think so . Because you forget Bandwidth, There  are network congestion probability when Http Message is over big.
Let us take an example:
In Redis world, If you query value  which has  a very bigger size ,The request takes a long time. The key is called big key.

> Your chunk size is 1MB, which means you cannot get a higher upload speed than 20MB / sec. Even if your upload of a single chunk is instant.

Finally,  chunk size is changable ,1 MB just is a default value ,not best value for everyone, you can change it

**Comment by SebastianStehle** [comment]
A ping has nothing to do with the bandwidth. It is the network delay to send a packet to a server and get pack the answer.

A good ping is 50ms. But if you go from one location to another you have higher latency: https://www.verizon.com/business/terms/latency/

So lets go with the example from verizon: Hongkong to US: **150ms**. 

Even if you would have an infinite bandwidth you can only make 6 HTTP requests per second, if you do them sequentially, because you have to deal with the latency. Because 1 sec = 1000ms. And 1000 ms / 150ms = 6.

 So with your 1MB chunk size you reduce the theoretically bandwidth from infinite to 6MB/s.

There are a lot of problems with this approach:

1. If you increase the chunk size, your application consumes much more memory because you have to keep the buffer in memory. https://github.com/bluetianx/BirdMessenger/blob/master/src/BirdMessenger/TusClient.cs#L101
2. You create a new buffer for each chunk, which is also not necessary. This creates a lot of allocations and puts pressure on the Garbage Collection. If you want to upload 1GB you allocate 1GB of memory. The garbage collector does not free up the memory immediately, which means that even if you only need 1 MB, you might see a very high memory usage until the memory is given backen to the operation system.
3. You create a lot of HTTP requests. Which puts unnecessary load the server. Because each request also needs to be authorized and database calls need to be be made and so on, which also causes high costs.

With streaming it is not necessary. I created a custom client as an extension method to HttpClient. My approach is to write a custom HttpContent which accepts a stream:

https://github.com/Squidex/assets/blob/tus-adapter/TusTestServer/Client/ProgressableStreamContent.cs

It can also report progress. This implementation consumes 4KB of memory and also allocates 4KB and has a much higher upload speed.

**Comment by bluetianx** [comment]
> With streaming it is not necessary. I created a custom client as an extension method to HttpClient. My approach is to write a custom HttpContent which accepts a stream:

Thank you very much for your patient communication, I'll take a look at your code,I also plan to address memory performance issues in the next version

**Comment by bluetianx** [comment]
@SebastianStehle  I have test your demo , It is great, You're a great programmer. I will improve the client in the next version based on your demo.

**Comment by SebastianStehle** [comment]
Thank you very much for your nice words: I have made a few improvements that i all need. I do not want to maintain a custom tus client, so if you integrate that, I will  switch to your implementation.

I have also created a few integration tests: https://github.com/Squidex/assets/blob/master/Squidex.Assets.Tests/TusServerTests.cs

**Comment by bluetianx** [comment]
> so if you integrate that 

No problem, I will

**Comment by bluetianx** [comment]
> I have also created a few integration tests:

copy that

**Comment by bluetianx** [comment]
The client has supported streaming, I  will release 2.2.0 version.  I am going to develop 3.0 version , In 3.0 version ,client will be simpler and more efficient.  I will resolve the [issue](https://github.com/bluetianx/BirdMessenger/issues/38)
