### ISSUE TITLE
文件上传完成之后，客户端如何得到Http返回值？

### ISSUE THREAD

**Issue by n27741** [bluetianx/BirdMessenger#44]
我用了你BirdMessager效果很赞。

我有一个疑问，文件上传之后，服务器给文件赋予了一个整数ID，作为标识。
如何才能得到服务器的Http返回值呢？

我现在的做法是，客户端产生一个GUID，放到TUSHeader里面随文件一起传上去，服务器存文件之后,产生文件ID，将GUID和文件ID存入数据库。

然后客户端在文件传输完成事件中，再去用GUID做为参数请求一个新的WebAPI获得文件ID，有没有可能，文件存完之后，服务器返回业务生成的ID值给客户端？

谢谢。

**Comment by bluetianx** [comment]
> 我用了你BirdMessager效果很赞。

谢谢 夸奖

> 文件上传之后，服务器给文件赋予了一个整数ID，作为标识

为什么要用整数ID？， var fileUrl = await tusClient.Create(fileInfo,null,requestOption);
fileUrl 做标识 也可以考虑用的。

> 有没有可能，文件存完之后，服务器返回业务生成的ID值给客户端？

目前client 还没返回服务端的Http 响应数据，不过这个功能会在下个版本支持的

**Comment by bluetianx** [comment]
@n27741 现在最新的版本已经支持了你的诉求
