### ISSUE TITLE
Nuget Pakage 3.0 is not 3.0 in github

### ISSUE THREAD

**Issue by thsdmfwns** [bluetianx/BirdMessenger#46]
I installed BirdMessenger by Pakage Manager and my .csproj file is 

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BirdMessenger" Version="3.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="6.0.0" />
  </ItemGroup>

</Project>
```

I cant find namespace of TusCreateRequestOption, TusCreateAsync and others !
I think the BirdMessenger in Nuget Pakage is not 3.0.0 but 2.X

**Comment by bluetianx** [comment]
> I cant find namespace of TusCreateRequestOption, TusCreateAsync and others

That has been discarded since 3.0.0 , You can get samples  from [Unitest](https://github.com/bluetianx/BirdMessenger/blob/master/src/BirdMessenger.Test/HttpClientExtensionTest.cs)
 or demo [Code](https://github.com/bluetianx/BirdMessenger/tree/master/samples)

**Comment by CaffeineDaemon** [comment]
@bluetianx i think you misunderstood the question.
Please take a look at the package contents of the BirdMessenger 3.0 package on nuget.org [https://www.fuget.org/packages/BirdMessenger/3.0.0](https://www.fuget.org/packages/BirdMessenger/3.0.0)
Its missing the types used in the unit tests and code examples examples you have linked to and instead contains the BirdMessenger 2.2.x types.
It looks like something got mixed up and the old 2.2.x code got published as the version 3.0 package.

The 3.0-beta1 package also has the wrong contents [https://www.fuget.org/packages/BirdMessenger/3.0.0-beta1](https://www.fuget.org/packages/BirdMessenger/3.0.0-beta1)
Maybe there is something wrong with you publishing script or workflow.

**Comment by bluetianx** [comment]
> I cant find namespace of TusCreateRequestOption,

I think you want to tell me you **can not**.  I  got you now; It is my fault.  Thank you for your issue.

**Comment by bluetianx** [comment]
I have fixed the serious bug, I executed command **dotnet pack -c Release** for building package since v3.0beta, but It dose not work as I expected. I do not know why. I fixed it with command **dotnet build -c Release**. 
I will be very careful  and verify package before publishing package to nuget
