### ISSUE TITLE
Chunked upload in v3

### ISSUE THREAD

**Issue by jonaskaltenbachz** [bluetianx/BirdMessenger#47]
Hello,
is there also in version 3.x the possibility to disable streaming and upload files with a fixed chunk size (like in version 2)? 
If no, is it planned to implement this in the future? 

Thank you and best regards,
Jonas

**Comment by bluetianx** [comment]
I will implement that if you really need it, I wonder why do not you upload files with streaming,  I think Streaming is more efficient than chunk

**Comment by quality-leftovers** [comment]
Hi,

Maybe you can explain how the current upload mechanism is intended to work for big files. I'm having a bit of a problem understanding how it will works, too.

It seems v3 currently only does a single PATCH request to the server for an upload (multiple calls to TusPatchAsync seem to not be intended since a HEAD request is also used to set stream offset).

Given a big upload (>= 1 Gib) wouldn't
- the server time out the request since it takes too long for the client to upload (e.g. the reference tusd go implementation has a default timeout of a few minutes)
- wouldn't the whole request be lost when PATCH request is interrupted when uploading data to the tusd go reference server implementation? To me it looks like the store implementations only write a chunk after the complete PATCH request has been read
- simple tusd servers that read HTTP requests into memory would run out of memory pretty fast

I always thought tusd resume functionality relied on there being multiple PATCH requests being made by the client. But maybe I'm mistaken.

I might have major gaps in my understanding of the API package and be mis-using it, though :P

**Comment by bluetianx** [comment]
Hi
you can check this [issue](https://github.com/bluetianx/BirdMessenger/issues/39) ,and then  maybe you will understand,
I look forward to discussing this with you.

**Comment by quality-leftovers** [comment]
I see. Those are very good points regarding optimization of throughput. 

Now let me give a short introduction on what we are doing and why we created this ticket: Recently we upgraded to BirdMessenger v3 and our uploads to our local tusd reference test server started to fail. We are using azure store backend and had no problems using BirdMessenger v2.

We did some digging in the tusd code today and it seems azure store wants to read the complete body of a patch request before it commits it as azure block blob (see: https://github.com/tus/tusd/tree/master/pkg/azurestore).

```go
func (upload *AzUpload) WriteChunk(ctx context.Context, offset int64, src io.Reader) (int64, error) {
	r := bufio.NewReader(src)
	buf := new(bytes.Buffer)
	n, err := r.WriteTo(buf)
	if err != nil {
		return 0, err
	}
       //!COMMENT quality-leftovers: reading the complete chunk size here, BEFORE committing data to azure store
	chunkSize := int64(binary.Size(buf.Bytes())) /
	if chunkSize > MaxBlockBlobChunkSize {
		return 0, fmt.Errorf("azurestore: Chunk of size %v too large. Max chunk size is %v", chunkSize, MaxBlockBlobChunkSize)
	}

	re := bytes.NewReader(buf.Bytes())
	err = upload.BlockBlob.Upload(ctx, re)
	if err != nil {
		return 0, err
	}

	upload.InfoHandler.Offset += n
	return n, nil
}
```

On the other hand other stores like s3 seem to support storing partial chunk data:
```go
func (upload s3Upload) WriteChunk(ctx context.Context, offset int64, src io.Reader) (int64, error) {
	id := upload.id
	store := upload.store

	uploadId, multipartId := splitIds(id)

	// Get the total size of the current upload
	info, err := upload.GetInfo(ctx)
	if err != nil {
		return 0, err
	}

	size := info.Size
	bytesUploaded := int64(0)
	optimalPartSize, err := store.calcOptimalPartSize(size)
	if err != nil {
		return 0, err
	}

	// Get number of parts to generate next number
	parts, err := store.listAllParts(ctx, id)
	if err != nil {
		return 0, err
	}

	numParts := len(parts)
	nextPartNum := int64(numParts + 1)

	incompletePartFile, incompletePartSize, err := store.downloadIncompletePartForUpload(ctx, uploadId)
	if err != nil {
		return 0, err
	}
	if incompletePartFile != nil {
		defer cleanUpTempFile(incompletePartFile)

		if err := store.deleteIncompletePartForUpload(ctx, uploadId); err != nil {
			return 0, err
		}

		src = io.MultiReader(incompletePartFile, src)
	}

	fileChan := make(chan *os.File, store.MaxBufferedParts)
	doneChan := make(chan struct{})
	defer close(doneChan)

	// If we panic or return while there are still files in the channel, then
	// we may leak file descriptors. Let's ensure that those are cleaned up.
	defer func() {
		for file := range fileChan {
			cleanUpTempFile(file)
		}
	}()

	partProducer := s3PartProducer{
		store: store,
		done:  doneChan,
		files: fileChan,
		r:     src,
	}
	go partProducer.produce(optimalPartSize)

	for file := range fileChan {
		stat, err := file.Stat()
		if err != nil {
			return 0, err
		}
		n := stat.Size()

		isFinalChunk := !info.SizeIsDeferred && (size == (offset-incompletePartSize)+n)
		if n >= store.MinPartSize || isFinalChunk {
			uploadPartInput := &s3.UploadPartInput{
				Bucket:     aws.String(store.Bucket),
				Key:        store.keyWithPrefix(uploadId),
				UploadId:   aws.String(multipartId),
				PartNumber: aws.Int64(nextPartNum),
			}
			if err := upload.putPartForUpload(ctx, uploadPartInput, file, n); err != nil {
				return bytesUploaded, err
			}
		} else {
			if err := store.putIncompletePartForUpload(ctx, uploadId, file); err != nil {
				return bytesUploaded, err
			}

			bytesUploaded += n

			return (bytesUploaded - incompletePartSize), nil
		}

		offset += n
		bytesUploaded += n
		nextPartNum += 1
	}

	return bytesUploaded - incompletePartSize, partProducer.err
}
```

I'd argue that while using a single PATCH is technically better (and recommended) solution supporting multiple PATCH requests based on a "chunk size" limit is needed for the following reasons:
- it is doubtful all tus servers will be able to handle streaming big payloads
- some cloud service hosting solutions enforce HTTP request timeouts of ~240 seconds, which means all uploads that take longer than 240 seconds will always fail (at least initially)
- a server might not want a client to have a connection open for hours when he is on a slow connection and not support the upload progressing from received data of a single PATCH request

**Comment by bluetianx** [comment]
Thank you very much for your patient explanation.   I agree with you. I will implement it again, BirdMessenger should support different usage scenarios

**Comment by quality-leftovers** [comment]
Much appreciated, thank you very much. Also great heads up regarding streaming. Didn't understand why it was dropped. Interesting read.

**Comment by bluetianx** [comment]
I have finished it in v3.1.0. If you have any questions, please let me know soon. @quality-leftovers  @jonaskaltenbachz

**Comment by jonaskaltenbachz** [comment]
Thanks for the quick fix @bluetianx. We will test it soon in detail but a first short test looks very good. 
Thank you very much!
