### ISSUE TITLE
请问如何调用BirdMessenger进行重传？

### ISSUE THREAD

**Issue by n27741** [bluetianx/BirdMessenger#48]
hi bluetianx

我使用你写的httpclient上传文件到服务器的函数是ok的。

但是，我模拟中断上传，然后重传同一个文件，程序每次都是重新传输传输文件。没有接着上次已经传过的位置进行resume断点续传。

请问有这样功能的demo或者说明吗？需要特别设置什么属性吗？

**Comment by n27741** [comment]
哦 sorry，我找到了。

你的Demo中

 
                TusCreateResponse response = await _httpClient.TusCreateAsync(tusCreateRequestOption, _cancellationTokenSource.Token);
             
这段每次都是产生新的FileLocation

只要把要重试的FileLocation记录下来


 TusPatchRequestOption tusPatchRequestOption = new TusPatchRequestOption()
            {
                FileLocation = _uri,   <------这里设置要重传的uri即可；
                Stream = fileStream,

**Comment by bluetianx** [comment]
是的，抱歉刚看到你的issue
