### ISSUE TITLE
从BirdMessenger2.2.1升级到BirdMessenger3.1.0程序出现异常

### ISSUE THREAD

**Issue by bidw77** [bluetianx/BirdMessenger#49]
您好！从BirdMessenger2.2.1升级到BirdMessenger3.1.0程序出现异常
![image](https://github.com/bluetianx/BirdMessenger/assets/73728460/1498f34e-63a9-44cb-9ef8-5265b32bc0ed)
OriginResponseMessage：
{StatusCode: 404, ReasonPhrase: 'Not Found', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Transfer-Encoding: chunked
  Connection: keep-alive
  Pragma: no-cache
  Cache-Control: no-store, no-cache
  Date: Wed, 17 May 2023 09:29:01 GMT
  Server: Tengine/2.3.3
  Content-Type: text/plain
  Expires: -1
}}

**Comment by bluetianx** [comment]
这个异常是404 异常，代表你的http请求地址不存在，检查对应的上传文件是否还存在

**Comment by bidw77** [comment]
用UploadType.Chunk上传成功。UploadType.Stream报上面的异常

**Comment by bluetianx** [comment]
应该是你的服务端不支持 stream 方式上传

**Comment by bidw77** [comment]
是的。调整了nginx配置就上传成功了。
