### ISSUE TITLE
Sample TestDotNetSite Issue

### ISSUE THREAD

**Issue by benny-adiwijaya** [bluetianx/BirdMessenger#50]
Hi, I want to try sample TestDotNetSite but it didn't have a web page. What do I need to do for the first step?

**Comment by bluetianx** [comment]
Hi, TestDotNetSite dose not have web page,If you successfully run this project, you can upload a file with URL(http://host(your website host)/files).

**Comment by bluetianx** [comment]
You can refer to BirdMessenger.Test project code
