### ISSUE TITLE
How to specificy upload offset for 

### ISSUE THREAD

**Issue by erenturkm** [bluetianx/BirdMessenger#53]
Hi,

I am trying to implement a client. The client keeps track of the uploaded bytes. 
From https://github.com/bluetianx/BirdMessenger/issues/52#issuecomment-1695840278 I understand that I should be able to provide upload-offset to patch request option to start from a given offset for failed upload attempts. However couldn't find  a way to do it.

**Comment by bluetianx** [comment]
>  I am trying to implement a client. The client keeps track of the uploaded bytes.

you should set  OnCompletedAsync field ,sample codes as follows

```
TusPatchRequestOption tusPatchRequestOption = new TusPatchRequestOption
            {
                FileLocation = resp.FileLocation,
                Stream = fileStream,
                //UploadBufferSize = 2*1024*1024, // upload size ,default value is 1MB
                //UploadType = UploadType.Chunk,  // setting upload file with Stream or chunk ,default value is Stream
                OnProgressAsync = x =>
                {
                    var uploadedProgress = (int)Math.Floor(100 * (double)x.UploadedSize / x.TotalSize);
                    Console.WriteLine($"OnProgressAsync-TotalSize:{x.TotalSize}-UploadedSize:{x.UploadedSize}-uploadedProgress:{uploadedProgress}");
                    return Task.CompletedTask;
                },
                OnCompletedAsync = x =>
                {
                    var reqOption = x.TusRequestOption as TusPatchRequestOption;
                    Console.WriteLine($"File:{reqOption.FileLocation} Completed ");
                    return Task.CompletedTask;
                },
                OnFailedAsync = x =>
                {
                    Console.WriteLine($"error： {x.Exception.Message}");
                    if (x.OriginHttpRequestMessage is not null)
                    {
                        //log httpRequest
                    }

                    if (x.OriginResponseMessage is not null)
                    {
                        //log response
                    }
                    return Task.CompletedTask;
                }
            };

            var tusPatchResp = await tusClient.TusPatchAsync(tusPatchRequestOption, CancellationToken.None);
```

**Comment by erenturkm** [comment]
I think I wasnt clear so providing better explanation. I want to be able to resume the upload when I restart the tool.

1) I wrote command line tool as the client that keeps track of how much bytes are uploaded to the server by persisting to a file inside OnProgressAsync.
2) When the connection is lost (I simulate by Cntrl-C) file has the pointer of last successfully uploaded bytes.
3) I implemented timeout on server side from [https://github.com/tusdotnet/tusdotnet/wiki/Configure-Kestrel   ](url)
4)  When I restart the tool, get the file Id and uploaded bytes from the state file.
5) Instead of doing a TusCreateAsync, I understand that I need to fill in the TusPatchRequestOption, but I am struggling to give the paramaters correctly.
6) I give the FileLocation from my state file, (If I give UploadType chunk, I get an error  Received an invalid status line: 'HTTP/1.1 0 '.)
7) TusPatchAsync starts from the beginning of file, and I receive "Error while copying content to a stream." in the middle of the stream.

What am I doing wrong here?

**Comment by bluetianx** [comment]
> I want to be able to resume the upload when I restart the tool.

1. invoking TusCreateAsync. for getting a  FileLocation of response,and saving it,
2. If your client restarts, and you can resume the upload  by only invoking  TusPatchAsync with FileLocation you saved, DO NOT invoke TusCreateAsync again

**Comment by bluetianx** [comment]
You can refer it  https://github.com/bluetianx/BirdMessenger/blob/0c92afab65fe33ab41a743050d687968637218ad/src/BirdMessenger.Test/HttpClientExtensionTest.cs#L217C17-L217C17
