### ISSUE TITLE
TusPatchAsync returns empty

### ISSUE THREAD

**Issue by erenturkm** [bluetianx/BirdMessenger#54]
Hi,

I am trying to catch the error case when resumed file upload is requested but partial uploaded file is not present on the server.  When
`
var tusPatchResp = await httpClient.TusPatchAsync(TPRO, CancellationToken.None);
`
is called, it returns empty tusPatchResponse and print following on console
`
error: Response status code does not indicate success: 404 (Not Found).
`
I need this status code (404) returned from your function to act on it and believe this is a bug.

My interpretation looking at your code:
in file [HttpClientExtension.cs](https://github.com/bluetianx/BirdMessenger/blob/master/src/BirdMessenger/HttpClientExtension.cs)
inside function TusPatchWithStreamingAsync the code is filling tusPatchResponse after the catch block, so it returns and empty value. I think you want a finally block to fill it.

**Comment by bluetianx** [comment]
> TusPatchWithStreamingAsync the code is filling tusPatchResponse after the catch block, so it returns and empty value. I think you want a finally block to fill it.

 Thank your issue,I think it is a bug, But the reason is not what you think. The client invokes TusHeadAsync once for getting offset uploeaded before uploading the file. I think TusHeadAsync threwed an Exception

**Comment by bluetianx** [comment]
It has been fixed in v3.1.2
