### ISSUE TITLE
Support zero length uploads

### ISSUE THREAD

**Issue by creadth** [bluetianx/BirdMessenger#57]
Currently if UploadLength is set to zero without setting IsUploadDeferLength to true, the library will throw an error that "UploadLength should not be less than zero", so it is not possible to upload empty files without adjusting headers with OnPreSendRequestAsync event.

**Comment by bluetianx** [comment]
Why do you want to set UploadLength to zero without setting IsUploadDeferLength?  Can you tell me about it?

**Comment by creadth** [comment]
When user uploads a file with zero content, BirdMessenger is unable to process this request and fails. tus server and other libs handle this request correctly - uploading an empty file.

**Comment by bluetianx** [comment]
ok, I got it , I will deal with it

**Comment by bluetianx** [comment]
[tus-resumable-upload-protocol](https://github.com/tus/tus-resumable-upload-protocol](https://github.com/tus/tus-resumable-upload-protocol/issues/196)

**Comment by bluetianx** [comment]
@creadth , Upgrading BirdMessenger to 3.1.3 , Your problem will be resolved
