### ISSUE TITLE
no found header of Tus-Resumable

### ISSUE THREAD

**Issue by Julien-Marpault** [bluetianx/BirdMessenger#58]
I just updated Bird Messenger to V3.

Since I get an error: "no found header of Tus-Resumable"

But if I add the header to HttpHeaders I get this error: "HttpHeader can not contain tus Reserved word: Tus-Resumable"

Thanks

**Comment by bluetianx** [comment]
Hi, Can you show me a more detailed version

**Comment by ghost** [comment]
Hello, I recently had the same issue. It is happening when the TUS api returned a 401 or 403 (probably any 4xx or 5xx) in which case the header Tus-Resumable was not present in the response. I don't know if the api is at fault but if not I hope it can help you investigate that issue further. The server implementation is made with https://github.com/tusdotnet/tusdotnet.

**Comment by bluetianx** [comment]
ok, Thank you for your information,I will investigeate

**Comment by bluetianx** [comment]
@davidpg-bimone  by the way, which version of BirdMessenger do you use ?

**Comment by ghost** [comment]
It is the version 3.1.3
