### ISSUE TITLE
流式传输 在安卓上上传进度不对

### ISSUE THREAD

**Issue by Qiulin-Git** [bluetianx/BirdMessenger#59]
我使用 Maui Blazor  和 blazor WebAssembly  调用 BirdMessenger 上传，发现 在安卓上使用流式传输上传 50M 左右的文件 ，OnProgressAsync 返回的进度一下就到100%了，实际并没有完全上传 需要在100%等待好几秒才真正上传成功 ，如果上传100多M的文件会卡在100% 十几秒才上传成功

**Comment by bluetianx** [comment]
使用非流式传输会有这样的问题吗？

**Comment by Qiulin-Git** [comment]
> 使用非流式传输会有这样的问题吗？

使用 UploadType.Chunk  没问题

**Comment by bluetianx** [comment]
抱歉，我这边没有安卓测试平台，常见的net core 平台可以复现你的问题吗？

**Comment by Qiulin-Git** [comment]
> 抱歉，我这边没有安卓测试平台，常见的net core 平台可以复现你的问题吗？
我刚测试了，不单单是安卓上 ，Web 上也一样，我的云服务器只有1M宽带，在电脑浏览器里上传 110M 文件 ，使用流式上传进度会在2秒内从0到100，然后卡在100% 1分钟才上传完成

VS 新建一个 Blazor WebAssembly 项目 ，用 InputFile 组件上传 ，即可复现（服务器上传限速1M）

**Comment by Qiulin-Git** [comment]
> 抱歉，我这边没有安卓测试平台，常见的net core 平台可以复现你的问题吗？

我刚测试了，不单单是安卓上 ，Web 上也一样，我的服务器只有1M宽带，在电脑浏览器里上传 110M 文件 进度会在2秒内从0到100，然后卡在100% 1分钟才上传完成

VS 新建一个 Blazor WebAssembly 项目 ，用 InputFile 组件上传 ，即可复现

**Comment by bluetianx** [comment]
文件上传的服务端站点是运行同 上传文件应用的同一个机器吗？因为我基本上都是在本地机器测试的

**Comment by Qiulin-Git** [comment]
> 文件上传的服务端站点是运行同 上传文件应用的同一个机器吗？因为我基本上都是在本地机器测试的

不是， 服务端在云服务器上，云服务器只有1M的宽带

**Comment by bluetianx** [comment]
估计是云服务器的网关问题，一般云服务的网关对流式传输不太友好，之前也有个客户遇到过类似场景，我再研究一下

**Comment by bluetianx** [comment]
你也可以在本地机器上运行服务端应用，看看是否能复现问题

**Comment by Qiulin-Git** [comment]
> 你也可以在本地机器上运行服务端应用，看看是否能复现问题

本机运行没有问题

**Comment by bluetianx** [comment]
你先暂时用 UploadType.Chunk 模式传输吧，应该是云服务厂商的网关配置有关

**Comment by Qiulin-Git** [comment]
> 你先暂时用 UploadType.Chunk 模式传输吧，应该是云服务厂商的网关配置有关

好的
