### ISSUE TITLE
Uri generation in TusCreate fails if using HttpClient BaseAddress

### ISSUE THREAD

**Issue by craftbyte** [bluetianx/BirdMessenger#61]
We are running a service where the HttpClient BaseAddress is set at app startup with this:
```cs
builder.Services.AddHttpClient<ITusClient, TusClient>(client =>
{
    client.BaseAddress = new(builder.Configuration["Endpoint"] ?? "http://localhost:3000/");
    client.DefaultRequestHeaders.ConnectionClose = true;
}).SetHandlerLifetime(TimeSpan.FromMinutes(5))
.AddPolicyHandler(GetRetryPolicy()); ;
```
We then use the following to create an upload:
```cs
TusCreateRequestOption createOption = new()
{
    Metadata = metadataCollection,
    Endpoint = new Uri("upload/", UriKind.Relative),
    UploadLength = fs.Length
};
create = await tusClient.TusCreateAsync(createOption, cancellationToken);
```

Using these, we noticed that when the server returns a full (https://localhost:3000/upload/1234) URL, the upload works, but if the server returns a relative URL (/upload/1234), the call fails with the Uri failing to be constructed.

I think TusClient should also look at the BaseAddress of the HttpClient (if set) to determine the upload URL.

**Comment by bluetianx** [comment]
Good 👍 Issue

**Comment by bluetianx** [comment]
Actually, TusClient supports relative URL, TusClient combine EndPoint with URL from Response ,if The URL from Response is relative
